'use strict';
/* Generated by RIFTLang v1.0.0 - classical mode */
const rift = require('./bindings/node-riftlang/rift_binding.cjs');

// RIFT: classical mode
// rift: memory span (fixed, 4096 bytes)
// type: Counter
let counter = 0;
let max_count = 100;
// policy: counter_memory
while (counter < max_count) {
    counter = counter + 1;
}
rift.validate('counter');
