// Generated by RIFTLang v1.0.0 - classical mode
package main

import "fmt"

func main() {
	// RIFT: classical mode
	// rift: memory span (fixed, 4096 bytes)
	type Counter struct {
		value int32
		step int32
	}

	counter := 0
	max_count := 100
	// policy: counter_memory
	for counter < max_count {
		counter = counter + 1
	}
	fmt.Printf("rift.validate: %v\n", counter)
	_ = fmt.Sprintf  // suppress unused import
}
