-- Generated by RIFTLang v1.0.0 - classical mode
local rift = dofile('bindings/lua-riftlang/rift_binding.lua')

-- RIFT: classical mode
-- rift: memory span (fixed, 4096 bytes)
-- type: Counter
local counter = 0
local max_count = 100
-- policy: counter_memory
while counter < max_count do
    counter = counter + 1
end
rift.validate(counter)
