# -*- coding: utf-8 -*-
# Generated by RIFTLang v1.0.0 - classical mode
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                'bindings', 'pyriftlang'))
import rift_binding as rift

# RIFT: classical mode
# rift: memory span (fixed, 4096 bytes)
# type: Counter
counter = 0
max_count = 100
# policy: counter_memory
while counter < max_count:
    counter = counter + 1
rift.validate(counter)
