/* Generated by RIFTLang v1.0.0 - classical mode */
/* Policy threshold: 0.85 | Optimization: O1 */
#include "riftlang.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/* Policy governance context */
static RiftPolicyContext* g_policy_ctx = NULL;
static RiftResultMatrix2x2* g_policy_matrix = NULL;

static void rift_init_policy(void) {
    g_policy_matrix = rift_result_matrix_create(0.85);
    g_policy_ctx = rift_policy_context_create("rift_main", 0.85, true);
    g_policy_ctx->result_matrix = g_policy_matrix;
}

int main(int argc, char* argv[]) {
    (void)argc; (void)argv;
    rift_init_policy();

    /* Generated by RIFTLang v1.0.0 - classical mode */
    /* Policy threshold: 0.85 | Optimization: O1 */
    // UNMATCHED: #include "riftlang.h"
    // UNMATCHED: #include <stdio.h>
    // UNMATCHED: #include <stdlib.h>
    // UNMATCHED: #include <math.h>

    /* Policy governance context */
    // UNMATCHED: static RiftPolicyContext* g_policy_ctx = NULL;
    // UNMATCHED: static RiftResultMatrix2x2* g_policy_matrix = NULL;

    // UNMATCHED: static void rift_init_policy(void) {
    // UNMATCHED:     g_policy_matrix = rift_result_matrix_create(0.85);
    // UNMATCHED:     g_policy_ctx = rift_policy_context_create("rift_main", 0.85, true);
    // UNMATCHED:     g_policy_ctx->result_matrix = g_policy_matrix;
    }

    // UNMATCHED: int main(int argc, char* argv[]) {
    // UNMATCHED:     (void)argc; (void)argv;
    // UNMATCHED:     rift_init_policy();

    */

    /* RIFT: Classical mode enabled */

    // UNMATCHED:     RIFT_DECLARE_MEMORY(span, RIFT_SPAN_FIXED,
    /* UNMATCHED:     bytes: 4096, */
    /* UNMATCHED:     type: continuous */
    }

    /* RIFT type: \1 */ typedef struct {
    /* UNMATCHED:     value: INT, */
    /* UNMATCHED:     step: INT */
    }

    // UNMATCHED:     RIFT_ASSIGN_CLASSICAL(\1, \2);
    // UNMATCHED:     RIFT_ASSIGN_CLASSICAL(\1, \2);

    // UNMATCHED:     RiftPolicyContext* policy_\1 = rift_policy_context_create("\1", threshold, true);
    /* UNMATCHED:     default_access: [READ, WRITE], */
    /* UNMATCHED:     reassert_lock: after every operation */
    }

    while (
    // UNMATCHED:     RIFT_ASSIGN_CLASSICAL(\1, \2);
    }

    // UNMATCHED:     rift_policy_validate(policy_matrix, true, true)

    /* Policy cleanup */
    // UNMATCHED:     rift_policy_context_destroy(g_policy_ctx);
    // UNMATCHED:     rift_result_matrix_destroy(g_policy_matrix);
    // UNMATCHED:     return 0;
    }

    /* Policy cleanup */
    rift_policy_context_destroy(g_policy_ctx);
    rift_result_matrix_destroy(g_policy_matrix);
    return 0;
}
