/* Generated by RIFTLang v1.0.0 - classical mode */
/* Policy threshold: 0.85 | Optimization: O1 */
#include "riftlang.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/* Policy governance context */
static RiftPolicyContext* g_policy_ctx = NULL;
static RiftResultMatrix2x2* g_policy_matrix = NULL;

static void rift_init_policy(void) {
    g_policy_matrix = rift_result_matrix_create(0.85);
    g_policy_ctx = rift_policy_context_create("rift_main", 0.85, true);
    g_policy_ctx->result_matrix = g_policy_matrix;
}

int main(int argc, char* argv[]) {
    (void)argc; (void)argv;
    rift_init_policy();

    /* RIFT: Classical mode enabled */

    /* Policy cleanup */
    rift_policy_context_destroy(g_policy_ctx);
    rift_result_matrix_destroy(g_policy_matrix);
    return 0;
}
